### ISSUE TITLE
Would you consider adding a license?

### ISSUE THREAD

**Issue by jjb** [jbaudanza/action_dispatch-gz_static#5]
Hi Jonathan,

Would you be interested in adding a license to this project? Such as MIT, BSD, GPL? Some business folks at my company are doing some checks to make sure we have rights to everything.

If so, I can submit a PR.

Thanks!
John

**Comment by jbaudanza** [comment]
Yeah sure. I'm fine with putting this in the public domain.

fyi.. this gem is no longer necessary in Rails 4.2.

**Comment by jjb** [comment]
@jbaudanza :tada: https://github.com/jbaudanza/action_dispatch-gz_static/pull/6

**Comment by jjb** [comment]
(i did MIT instead of public domain so that all others are required to also use MIT... let me know if you actually prefer public domain)
